server:
  port: ${PORT:8888}
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIGS_LOCATION:https://github.com/sewah2012/cloud-native-project-configs}
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true